-- Act
DROP MATERIALIZED VIEW VMA_ACTE;
CREATE MATERIALIZED VIEW VMA_ACTE
REFRESH NEXT SYSDATE + 1/24/6 COMPLETE AS
SELECT a.identifiant,a.code,a.libelle,a.type,a.reference
FROM VA_ACTE@dblink_elabo_bidf a;
ALTER TABLE VMA_ACTE ADD CONSTRAINT VMA_ACTE_PK PRIMARY KEY (IDENTIFIANT);
ALTER TABLE VMA_ACTE ADD CONSTRAINT VMA_ACTE_UK_CODE UNIQUE (CODE);