-- Act
DROP MATERIALIZED VIEW "CLOTURE".VMA_ACTE;
CREATE MATERIALIZED VIEW "CLOTURE".VMA_ACTE
REFRESH NEXT SYSDATE + 1/24/6 COMPLETE AS
SELECT a.identifiant,a.code,a.libelle,a.operation,a.operation_date,a.declencheur
FROM VA_ACTE a;
ALTER TABLE VMA_ACTE ADD CONSTRAINT VMA_ACTE_PK PRIMARY KEY (IDENTIFIANT);
ALTER TABLE VMA_ACTE ADD CONSTRAINT VMA_ACTE_UK_CODE UNIQUE (CODE);