CREATE OR REPLACE PROCEDURE PA_DEVERROUILLER_ACTE (IDENTIFIANT IN VARCHAR2,TYPE_VERROU IN VARCHAR2,TABLE_CIBLE IN VARCHAR2) AS
BEGIN
    UT_BIDF_TAMP.PA_DEVERROUILLER_ACTE@dblink_elabo_bidf(IDENTIFIANT,TYPE_VERROU,TABLE_CIBLE);
END PA_DEVERROUILLER_ACTE;

CREATE OR REPLACE PROCEDURE PA_VERROUILLER_ACTE (IDENTIFIANT IN VARCHAR2,TYPE_VERROU IN VARCHAR2,TABLE_CIBLE IN VARCHAR2) AS
BEGIN
    UT_BIDF_TAMP.PA_VERROUILLER_ACTE@dblink_elabo_bidf(IDENTIFIANT,TYPE_VERROU,TABLE_CIBLE);
END PA_VERROUILLER_ACTE;