DROP ALIAS IF EXISTS PA_VERROUILLER_ACTE;
CREATE ALIAS PA_VERROUILLER_ACTE FOR "ci.gouv.dgbf.system.cloture.server.impl.Procedures.PA_VERROUILLER_ACTE";

DROP ALIAS IF EXISTS PA_DEVERROUILLER_ACTE;
CREATE ALIAS PA_DEVERROUILLER_ACTE FOR "ci.gouv.dgbf.system.cloture.server.impl.Procedures.PA_DEVERROUILLER_ACTE";

INSERT INTO VMA_ACTE (IDENTIFIANT,CODE,LIBELLE,REFERENCE,TYPE) VALUES ('1','1','1','1','ENGAGEMENT');
INSERT INTO VA_VERROU (IDENTIFIANT,ACTE_IDENTIFIANT,MOTIF,ACTIF,DATE_DEBUT,DATE_FIN) VALUES ('1','1','Raison 01',1, DATE '2000-1-1', DATE '2000-1-2');
INSERT INTO VA_VERROU (IDENTIFIANT,ACTE_IDENTIFIANT,MOTIF,ACTIF) VALUES ('2','1','Raison 02',1);

INSERT INTO VA_ACTE_DERNIERE_OPERATION (IDENTIFIANT,ACTE,OPERATION,OPERATION_DATE,DECLENCHEUR) VALUES ('1','1','DEVERROUILLAGE', DATE '2000-1-2', 'christian');
INSERT INTO VA_VERROU_DERNIERE_OPERATION (IDENTIFIANT,OPERATION,OPERATION_DATE,DECLENCHEUR) VALUES ('1','DEVERROUILLAGE', DATE '2000-1-2', 'christian');