DROP ALIAS IF EXISTS PA_VERROUILLER_ACTE;
CREATE ALIAS PA_VERROUILLER_ACTE FOR "ci.gouv.dgbf.system.cloture.server.impl.Procedures.PA_VERROUILLER_ACTE";

DROP ALIAS IF EXISTS PA_DEVERROUILLER_ACTE;
CREATE ALIAS PA_DEVERROUILLER_ACTE FOR "ci.gouv.dgbf.system.cloture.server.impl.Procedures.PA_DEVERROUILLER_ACTE";

INSERT INTO VMA_ACTE (IDENTIFIANT,CODE,LIBELLE,REFERENCE,TYPE) VALUES ('1','1','1','1','ENGAGEMENT');