DROP ALIAS IF EXISTS PA_EXECUTER_PROCEDURE;
CREATE ALIAS PA_EXECUTER_PROCEDURE FOR "ci.gouv.dgbf.system.cloture.server.impl.Procedures.PA_EXECUTER_PROCEDURE";

INSERT INTO TA_GROUPE_OPERATION(IDENTIFIANT,CODE,LIBELLE) VALUES ('E','E','Engagement');
INSERT INTO TA_GROUPE_OPERATION(IDENTIFIANT,CODE,LIBELLE) VALUES ('L','L','Liquidation');
INSERT INTO TA_GROUPE_OPERATION(IDENTIFIANT,CODE,LIBELLE) VALUES ('O','O','Ordonnancement');
INSERT INTO TA_GROUPE_OPERATION(IDENTIFIANT,CODE,LIBELLE) VALUES ('PC','PC','Prise en charge');

-- passed blocking
INSERT INTO TA_OPERATION(IDENTIFIANT,CODE,LIBELLE,GROUPE,DATE_DEBUT,PROCEDURE_LIBELLE) VALUES ('OPassedBlocking','OPassedBlocking','Verrouiller','E',DATE '2021-1-1','P');
-- passed non blocking
INSERT INTO TA_OPERATION(IDENTIFIANT,CODE,LIBELLE,GROUPE,DATE_DEBUT,PROCEDURE_LIBELLE) VALUES ('OPassedNonBlocking','OPassedNonBlocking','Verrouiller','E',DATE '2021-1-1','P');
-- future
INSERT INTO TA_OPERATION(IDENTIFIANT,CODE,LIBELLE,GROUPE,DATE_DEBUT,PROCEDURE_LIBELLE) VALUES ('OFuture','OFuture','Verrouiller','E',DATE '2099-1-1','P');

INSERT INTO TA_OPERATION(IDENTIFIANT,CODE,LIBELLE,GROUPE,DATE_DEBUT,PROCEDURE_LIBELLE,EXECUTION_STATUS) VALUES ('V01','V01','Verrouillage des engagements par bon de commande dont l''ordonnateur n''a pas fait la 1ere validation','E',DATE '2021-11-1','P','EN_COURS');
INSERT INTO TA_OPERATION(IDENTIFIANT,CODE,LIBELLE,GROUPE,DATE_DEBUT,PROCEDURE_LIBELLE) VALUES ('V02','V02','Verrouillage des engagements par bon de commande dont l''ordonnateur n''a pas fait la 2eme validation','E',DATE '2021-11-1','P');
INSERT INTO TA_OPERATION(IDENTIFIANT,CODE,LIBELLE,GROUPE,DATE_DEBUT,PROCEDURE_LIBELLE) VALUES ('V03','V03','Verrouillage des engagements direct hors Personnel, Abonnement et Dette non validés une première fois par l’Ordonnateur','E',DATE '2021-11-1','P');

INSERT INTO VMA_ACTE (IDENTIFIANT,CODE,LIBELLE,REFERENCE,TYPE) VALUES ('1','1','1','1','ENGAGEMENT');
INSERT INTO VA_VERROU (IDENTIFIANT,ACTE_IDENTIFIANT,MOTIF) VALUES ('1','1','Raison 01');
INSERT INTO VA_VERROU (IDENTIFIANT,ACTE_IDENTIFIANT,MOTIF) VALUES ('2','1','Raison 02');
INSERT INTO VA_ACTE_STATUT (IDENTIFIANT,NOMBRE_VERROU_ACTIF) VALUES ('1',1);