INSERT INTO VMA_TYPE_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('ENGAGEMENT','ENGAGEMENT','ENGAGEMENT');
INSERT INTO VMA_TYPE_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('LIQUIDATION','LIQUIDATION','LIQUIDATION');
INSERT INTO VMA_TYPE_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('MANDAT','MANDAT','MANDAT');
INSERT INTO VMA_TYPE_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('ORDRE_PAIEMENT','ORDRE_PAIEMENT','ORDRE_PAIEMENT');