INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','1');
INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','2','2');
INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','3','3');
INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE) VALUES ('4','4','UFR daloa');
INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE) VALUES ('5','5','CHR de Daloa');
INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE) VALUES ('6','6','6');