INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('1','2021',2021,'1','1','1','1');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('2','2021',2021,'1','1','2','2');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('3','2021',2021,'2','2','1','1');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('4','2021',2021,'2','2','2','2');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('5','2021',2021,'2','2','3','3');

INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('6','2022',2022,'1','1','1','1');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('7','2022',2022,'1','1','2','2');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('8','2022',2022,'2','2','1','1');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('9','2022',2022,'2','2','2','2');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('10','2022',2022,'2','2','3','3');
INSERT INTO VMA_IMPUTATION(IDENTIFIANT,EXERCICE,EXERCICE_ANNEE,ACTIVITE,ACTIVITE_CODE,NATURE_ECONOMIQUE,NATURE_ECONOMIQUE_CODE) VALUES ('11','2022',2022,'2','2','4','4');