CREATE TABLE "TA_GROUPE_OPERATION" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TA_GROUPE_OPERATION_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE, 
	 CONSTRAINT "TA_GROUPE_OPERATION_UK1" UNIQUE ("CODE") ENABLE
   );
   
CREATE TABLE "TA_OPERATION" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"GROUPE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DATE_DEBUT" DATE NOT NULL ENABLE, 
	"EXECUTEE_PAR" VARCHAR2(255 BYTE), 
	"EXECUTION_DATE_DEBUT" DATE, 
	"EXECUTION_DATE_FIN" DATE, 
	"PROCEDURE_LIBELLE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"EXECUTION_STATUS" VARCHAR2(255 BYTE), 
	 CONSTRAINT "TA_OPERATION_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE, 
	 CONSTRAINT "TA_OPERATION_UK1" UNIQUE ("CODE") ENABLE, 
	 CONSTRAINT "TA_OPERATION_FK1" FOREIGN KEY ("GROUPE")
	 REFERENCES "TA_GROUPE_OPERATION" ("IDENTIFIANT") ENABLE
   );

CREATE TABLE "TA_ACTE_OPERATION" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"ACTE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"OPERATION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"OPERATION_DATE" DATE NOT NULL ENABLE, 
	"DECLENCHEUR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TA_ACTE_OPERATION_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE
   );